name: "ha-psegli (Nicholas Tang)"
url: "https://github.com/ntang/ha-psegli"
maintainer: "Nicholas Tang"
description: "PSEG Long Island Home Assistant app repository (automation app + integration)"
version: "2.5.1.1"
homeassistant: "2024.8.0"
